export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const SELECTED_ITEM = 'SELECTED_ITEM';
export const NULL_SELECTED_ITEM = 'SELECTED_ITEM';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';